Repository uscuni/neatnet, pull requests merged in 2024-12, with the labels that each got.

#117 doc work + type hints in `artifact.one_remaining()`
  sgeop/artifacts.py
Labels: documentation

#120 Vectorized explode LineStrings into constituent pairwise segments
  sgeop/artifacts.py
Labels: enhancement, refactor & code maint

#116 doc work + type hints + refactor `simplify.simplify_{singletons, pairs}()`, etc.
  sgeop/simplify.py
Labels: documentation, refactor & code maint

#123 flag for global exception raising in debugging
  sgeop/simplify.py
  sgeop/tests/conftest.py
Labels: tests/CI

#125 doc work + type hints + refactor – `artifacts.py` -- dangles
  sgeop/artifacts.py
Labels: documentation, refactor & code maint

#128 docs/typehints/comments – `simplify.simplify_clusters()`
  sgeop/simplify.py
Labels: documentation

#127 docs & typehints - `artifacts.py.{ccss_special_case(), filter_connections()}`
  sgeop/artifacts.py
Labels: documentation, refactor & code maint

#133 use hierarchy to break the chains of nodes in consolidation
  data/aleppo_1133/simplified.parquet
  data/auckland_869/simplified.parquet
  data/bucaramanga_4617/simplified.parquet
  data/douala_809/simplified.parquet
  data/liege_1656/simplified.parquet
  data/slc_4881/simplified.parquet
  sgeop/nodes.py
  sgeop/tests/test_nodes.py
Labels: algo/method

#134 `mypy` type checking review, workflow, hook
  .github/workflows/mypy.yml
  .github/workflows/testing.yml
  .pre-commit-config.yaml
  sgeop/artifacts.py
  sgeop/continuity.py
  sgeop/geometry.py
  sgeop/nodes.py
  sgeop/simplify.py
  sgeop/tests/conftest.py
Labels: housekeeping

#132 ENH: keep the attributes around
  sgeop/nodes.py
  sgeop/simplify.py
  sgeop/tests/data/apalachicola_simplified_exclusion_mask.parquet
  sgeop/tests/data/apalachicola_simplified_standard.parquet
  sgeop/tests/test_simplify.py
Labels: algo/method

#136 Rename to neatnet
  .github/workflows/mypy.yml
  .github/workflows/testing.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  ci/py311_latest.yaml
  ci/py311_oldest.yaml
  ci/py312_latest.yaml
  ci/py313_dev.yaml
  ci/py313_latest.yaml
  ci_artifacts/apalachicola/simplified_exclusion_mask.parquet
  ci_artifacts/apalachicola/simplified_standard.parquet
  data/README.md
  data/generate_simplified.py
  environment.yml
  neatnet/__init__.py
  neatnet/artifacts.py
  neatnet/continuity.py
  neatnet/geometry.py
  neatnet/nodes.py
  neatnet/simplify.py
  neatnet/tests/conftest.py
  neatnet/tests/data/apalachicola_original.parquet
  neatnet/tests/data/apalachicola_simplified_exclusion_mask.parquet
  neatnet/tests/data/apalachicola_simplified_standard.parquet
  neatnet/tests/test_artifacts.py
  neatnet/tests/test_continuity.py
  neatnet/tests/test_geometry.py
  neatnet/tests/test_nodes.py
  neatnet/tests/test_simplify.py
  pyproject.toml
Labels: housekeeping

#146 rm ci_artifacts
  .gitignore
  ci_artifacts/apalachicola/simplified_exclusion_mask.parquet
  ci_artifacts/apalachicola/simplified_standard.parquet
Labels: housekeeping

#147 add projected CRS meters info – #142
  neatnet/simplify.py
Labels: documentation

#150 standardize input FUA indices & columns
  data/aleppo_1133/original.parquet
  data/aleppo_1133/simplified.parquet
  data/auckland_869/original.parquet
  data/auckland_869/simplified.parquet
  data/bucaramanga_4617/original.parquet
  data/bucaramanga_4617/simplified.parquet
  data/douala_809/original.parquet
  data/douala_809/simplified.parquet
  data/liege_1656/original.parquet
  data/liege_1656/simplified.parquet
  data/slc_4881/original.parquet
  data/slc_4881/simplified.parquet
  neatnet/tests/test_simplify.py
Labels: housekeeping

#151 BUG: fix Wuhan crash
  neatnet/nodes.py
Labels: rough edge

#154 small refactor in `artifacts.nx_gx()`
  neatnet/artifacts.py
Labels: refactor & code maint
