Repository uscuni/neatnet, pull requests merged in 2024-10, with the labels that each got.

#17 kickoff infrastructure, CI, & packaging
  .github/workflows/testing.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  ci/py310_sgeop-oldest.yaml
  ci/py311_sgeop-latest.yaml
  ci/py312_sgeop-dev.yaml
  ci/py312_sgeop-latest.yaml
  environment.yml
  pyproject.toml
Labels: housekeeping

#24 testing for `geometry.angle_between_two_lines()`
  sgeop/geometry.py
  sgeop/tests/test_geometry.py
Labels: tests/CI, refactor & code maint

#34 add pyarrow as a testing req
  ci/py311_sgeop-oldest.yaml
  environment.yml
  pyproject.toml
Labels: housekeeping, tests/CI

#36 revert 2 commits - resolve #35
  sgeop/nodes.py
  sgeop/simplify.py
Labels: bug

#29 small integrated testing data - apalachicola, fl
  sgeop/tests/data/apalachicola_original.parquet
  sgeop/tests/data/apalachicola_simplified.parquet
  sgeop/tests/test_simplify.py
Labels: tests/CI

#27 first round `geometry.voronoi_skeleton()` tests
  README.md
  codecov.yml
  sgeop/geometry.py
  sgeop/tests/conftest.py
  sgeop/tests/test_geometry.py
  sgeop/tests/test_simplify.py
Labels: tests/CI, refactor & code maint

#42 CI: codecov
  .github/workflows/testing.yml
Labels: housekeeping

#44 ensure index is integer from `nodes.split()`
  data/aleppo_1133/simplified.parquet
  data/bucaramanga_4617/simplified.parquet
  data/douala_809/simplified.parquet
  data/slc_4881/simplified.parquet
  sgeop/nodes.py
  sgeop/tests/data/apalachicola_simplified.parquet
  sgeop/tests/test_simplify.py
Labels: refactor & code maint

#45 Create CONTRIBUTING.md -- document procedure
  CONTRIBUTING.md
  README.md
Labels: documentation

#46 chip away some refactors in `geometry.py`
  sgeop/geometry.py
  sgeop/tests/test_geometry.py
Labels: tests/CI, refactor & code maint

#51 address #47 -- pandas DeprecationWarning
  sgeop/simplify.py
Labels: refactor & code maint

#50 dedicated minimal tests for `continuity.py`
  sgeop/continuity.py
  sgeop/tests/test_continuity.py
Labels: tests/CI, refactor & code maint

#53 full coverage for `geometry.py` with minimal tests
  pyproject.toml
  sgeop/tests/test_geometry.py
Labels: tests/CI

#54 update keyword in `voronoi_skeleton()`
  sgeop/artifacts.py
  sgeop/geometry.py
Labels: documentation, refactor & code maint

#57 dedicated minimal tests -- `nodes.get_components()`
  sgeop/geometry.py
  sgeop/nodes.py
  sgeop/tests/test_nodes.py
Labels: tests/CI

#58 dedicated minimal tests -- `nodes.weld_edges()`
  sgeop/nodes.py
  sgeop/tests/test_nodes.py
Labels: tests/CI

#63 `simplify.py` -- swap order of `simplify_clusters()` & `simplify_pairs()`
  sgeop/simplify.py
Labels: refactor & code maint

#59 dedicated minimal tests -- `nodes.remove_false_nodes()`
  sgeop/nodes.py
  sgeop/tests/test_nodes.py
Labels: tests/CI

#65 swap all `limit_distance` to `clip_limit`
  sgeop/artifacts.py
  sgeop/simplify.py
Labels: refactor & code maint
