Repository uscuni/neatnet, pull requests merged in 2025-02, with the labels that each got.

#152 TST: test wuhan on nightly and push to main
  .github/workflows/testing.yml
  data/generate_simplified.py
  data/wuhan_8989/original.parquet
  data/wuhan_8989/simplified.parquet
  neatnet/tests/test_simplify.py
  pixi.lock
  pyproject.toml
Labels: tests/CI

#160 initial pass at docs
  .gitignore
  docs/Makefile
  docs/make.bat
  docs/source/_static/custom.css
  docs/source/_static/icon.png
  docs/source/_static/logo.svg
  docs/source/_static/references.bib
  docs/source/api.rst
  docs/source/conf.py
  docs/source/index.md
  docs/source/intro.ipynb
  docs/source/references.rst
  neatnet/__init__.py
  neatnet/artifacts.py
  neatnet/simplify.py
  pixi.lock
  pyproject.toml
Labels: documentation

#173 GHA automated doc building and publishing
  .github/workflows/build_docs.yml
  ci/py313_latest.yaml
Labels: documentation, housekeeping
