Repository uscuni/neatnet, pull requests merged in 2025-03, with the labels that each got.

#174 DOC: expand documentation + fix a corner case
  README.md
  ci/py311_latest.yaml
  ci/py311_oldest.yaml
  ci/py312_latest.yaml
  ci/py313_dev.yaml
  ci/py313_latest.yaml
  data/aleppo_1133/simplified.parquet
  data/auckland_869/simplified.parquet
  data/bucaramanga_4617/simplified.parquet
  data/douala_809/simplified.parquet
  data/liege_1656/simplified.parquet
  data/slc_4881/simplified.parquet
  docs/source/intro.ipynb
  docs/source/simple_preprocessing.ipynb
  neatnet/geometry.py
  neatnet/tests/conftest.py
  neatnet/tests/test_simplify.py
  pixi.lock
  pyproject.toml
Labels: bug, documentation

#179 fill placeholders in contributing guide
  CONTRIBUTING.md
Labels: documentation

#180 funding note
  README.md
Labels: documentation

#178 fix _as_parts
  data/auckland_869/simplified.parquet
  neatnet/geometry.py
  neatnet/simplify.py
Labels: bug

#191 code health checkup -- docstring, type-hints, signatures
  neatnet/artifacts.py
  neatnet/gaps.py
  neatnet/nodes.py
  neatnet/simplify.py
  neatnet/tests/test_gaps.py
  pixi.lock
  pyproject.toml
Labels: documentation, housekeeping

#193 fix non-planar intersection in loops
  neatnet/nodes.py
  neatnet/tests/test_nodes.py
Labels: algo/method, rough edge
