Repository uscuni/neatnet, pull requests merged in 2025-05, with the labels that each got.

#201 add default artifact_threshold_fallback
  neatnet/artifacts.py
  neatnet/simplify.py
  neatnet/tests/test_simplify.py
Labels: refactor & code maint, rough edge

#202 Update simplify.py - docstring artifact_threshold_fallback
  neatnet/simplify.py
Labels: documentation

#207 dependency & docs health check-up
  .pre-commit-config.yaml
  ci/py313_latest.yaml
  docs/source/api.rst
  docs/source/conf.py
  docs/source/intro.ipynb
  docs/source/simple_preprocessing.ipynb
  environment.yml
  pyproject.toml
Labels: documentation, housekeeping

#216 PERF: nodes from LineString gdf
  neatnet/nodes.py
  neatnet/simplify.py
  pixi.lock
Labels: refactor & code maint

#223 fix for litany of `UserWarning: CRS not set...` warnings
  neatnet/artifacts.py
  neatnet/nodes.py
Labels: housekeeping, refactor & code maint

#231 docstring work and input clarifications
  neatnet/artifacts.py
  neatnet/continuity.py
  neatnet/nodes.py
  neatnet/simplify.py
  neatnet/tests/test_artifacts.py
Labels: documentation
